### ISSUE TITLE
Epic: polish ro crate profiles

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/arc-ro-crate-profile#1]
- [ ] ARC Profile
  - [x] nfdi4plants/arc-ro-crate-profile#2
  - [ ] nfdi4plants/arc-ro-crate-profile#3
  - [x] nfdi4plants/arc-ro-crate-profile#4
  - [ ] nfdi4plants/arc-ro-crate-profile#5

- [ ] ISA Profile
  - [x] nfdi4plants/isa-ro-crate-profile#30
  - [x] nfdi4plants/isa-ro-crate-profile#31
  - [ ] nfdi4plants/isa-ro-crate-profile#32
  - [x] nfdi4plants/isa-ro-crate-profile#33

- [ ] ARC-CWL Profile
  - [x] nfdi4plants/arc-cwl-ro-crate-profile#7
  - [ ] nfdi4plants/arc-cwl-ro-crate-profile#11
  - [ ] nfdi4plants/arc-cwl-ro-crate-profile#8
  - [ ] nfdi4plants/arc-cwl-ro-crate-profile#9
  - [ ] nfdi4plants/arc-cwl-ro-crate-profile#10
  - [ ] nfdi4plants/arc-cwl-ro-crate-profile#12

**Comment by kMutagene** [comment]
cc @HLWeil @muehlhaus

**Comment by kMutagene** [comment]
@hlweil i think you worked on many of the listed still open sub-issues, can you check whether some are done?
